---
abstract: 'Catalyst based application'
author:
  - 'Ruslan Zakirov'
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Globus
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Model::DBIC::Schema: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::StackTrace: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Plugin::Unicode: 0
  Catalyst::Runtime: 5.7015
  Catalyst::View::TT: 0
  Class::Date: 0
  Config::General: 0
  DBD::SQLite: 0
  DBIx::Class: 0
  SQL::Translator: 0
  Text::Unidecode: 0
  ex::lib: 0
  parent: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
